"""
FastAPI service.

Endpoints
---------
GET  /health              liveness + model status (what a load balancer polls)
POST /score               score one transaction, returns decision + reasons
POST /score/batch         score up to 1000 transactions in one call
GET  /metrics/model       offline evaluation metrics of the deployed model
GET  /customers/{id}      the behavioural profile the model is reasoning over
GET  /docs                interactive OpenAPI UI (generated by FastAPI)

Run with:  uvicorn api:app --reload --port 8000
"""
from __future__ import annotations

import json
import logging
import pathlib
import time
import uuid
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

from schemas import Transaction, ScoreResponse, BatchRequest, BatchResponse
from service import RiskScorer, ROOT

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("risk-api")

state: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the model once at startup, not per request."""
    t0 = time.perf_counter()
    scorer = RiskScorer()
    seeded = scorer.history.seed_from_csv(ROOT / "data" / "transactions.csv")
    state["scorer"] = scorer
    state["started_at"] = time.time()
    log.info("model=%s loaded in %.0f ms, seeded %s history rows for %s customers",
             scorer.model_name, (time.perf_counter() - t0) * 1000,
             seeded, scorer.history.customers)
    yield
    state.clear()


app = FastAPI(
    title="Financial Transaction Risk Analyzer",
    description="ML + rules hybrid scoring service for suspicious transaction detection.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.middleware("http")
async def add_correlation_id(request: Request, call_next):
    """Every request gets a traceable id — standard practice in bank estates."""
    rid = request.headers.get("x-correlation-id", str(uuid.uuid4()))
    t0 = time.perf_counter()
    response = await call_next(request)
    response.headers["x-correlation-id"] = rid
    log.info("%s %s -> %s in %.1f ms [%s]", request.method, request.url.path,
             response.status_code, (time.perf_counter() - t0) * 1000, rid)
    return response


@app.exception_handler(Exception)
async def unhandled(request: Request, exc: Exception):     # pragma: no cover
    log.exception("unhandled error")
    return JSONResponse(status_code=500,
                        content={"detail": "internal error", "type": type(exc).__name__})


@app.get("/health", tags=["ops"])
def health():
    s = state.get("scorer")
    return {
        "status": "ok" if s else "degraded",
        "model_loaded": s is not None,
        "model_version": s.model_name if s else None,
        "decision_threshold": round(s.threshold, 4) if s else None,
        "customers_in_history": s.history.customers if s else 0,
        "uptime_seconds": round(time.time() - state.get("started_at", time.time()), 1),
    }


@app.post("/score", response_model=ScoreResponse, tags=["scoring"])
def score(txn: Transaction):
    scorer: RiskScorer = state["scorer"]
    payload = txn.model_dump()
    payload["timestamp"] = txn.timestamp.isoformat()
    payload["home_country"] = txn.home_country or txn.country
    try:
        return scorer.score(payload)
    except Exception as exc:
        log.exception("scoring failed")
        raise HTTPException(status_code=422, detail=f"could not score: {exc}")


@app.post("/score/batch", response_model=BatchResponse, tags=["scoring"])
def score_batch(req: BatchRequest):
    scorer: RiskScorer = state["scorer"]
    results = []
    for t in req.transactions:
        p = t.model_dump()
        p["timestamp"] = t.timestamp.isoformat()
        p["home_country"] = t.home_country or t.country
        results.append(scorer.score(p))
    return {"results": results,
            "flagged": sum(r["decision"] != "ALLOW" for r in results),
            "count": len(results)}


@app.get("/metrics/model", tags=["ops"])
def model_metrics():
    path = ROOT / "artifacts" / "metrics.json"
    if not path.exists():
        raise HTTPException(404, "metrics not found — run train.py first")
    return json.loads(path.read_text())


@app.get("/customers/{customer_id}", tags=["scoring"])
def customer_profile(customer_id: str):
    scorer: RiskScorer = state["scorer"]
    hist = scorer.history.get(customer_id)
    if not hist:
        raise HTTPException(404, "no history for this customer")
    amounts = [h["amount"] for h in hist]
    return {
        "customer_id": customer_id,
        "transactions_held": len(hist),
        "median_amount": round(sorted(amounts)[len(amounts) // 2], 2),
        "max_amount": round(max(amounts), 2),
        "countries_seen": sorted({h["country"] for h in hist}),
        "devices_seen": len({h["device_id"] for h in hist}),
        "last_transaction_at": max(h["timestamp"] for h in hist).isoformat(),
    }
